### ISSUE TITLE
Submitting builds to Copr fails.

### ISSUE THREAD

**Issue by user501254** [rpm-software-management/tito#204] opened 2015-11-30 23:45 UTC
src.rpm uploads to Copr fails.
Build directory in use: default (ie. /tmp/tito)

Error log:

```
[ashesh@MISTRI paper-icon-theme] $ tito release paper-icon-theme
Will release to the following targets: paper-icon-theme
Releasing to target: paper-icon-theme
WARNING: unable to lookup latest package tag, building untagged test project
WARNING: .tito/packages/paper-icon-theme doesn't exist in git, using current directory
Working in: /tmp/tito/release-paper-icon-themeknsdumvc
Building release in Copr...
Wrote: /tmp/tito/paper-icon-theme-git-0.4460ee8.tar.gz
warning: line 26: second Group
warning: line 26: second Group

Wrote: /tmp/tito/paper-icon-theme-1.0-1.src.rpm


Uploading src.rpm.

Submiting build into Copr.
ERROR: Error running command: /usr/bin/copr-cli build paper-icon-theme paper-icon-theme-1.0-1.src.rpm

Status code: 1

Command output: 
Something went wrong:
Error: [Errno 2] No such file or directory: 'paper-icon-theme-1.0-1.src.rpm'

Traceback (most recent call last):
  File "/usr/bin/tito", line 23, in <module>
    CLI().main(sys.argv[1:])
  File "/usr/lib/python3.4/site-packages/tito/cli.py", line 220, in main
    return module.main(argv)
  File "/usr/lib/python3.4/site-packages/tito/cli.py", line 613, in main
    scratch=self.options.scratch)
  File "/usr/lib/python3.4/site-packages/tito/release/main.py", line 465, in release
    self._koji_release()
  File "/usr/lib/python3.4/site-packages/tito/release/copr.py", line 48, in _koji_release
    KojiReleaser._koji_release(self)
  File "/usr/lib/python3.4/site-packages/tito/release/main.py", line 532, in _koji_release
    self._submit_build(self.executable, koji_opts, koji_tag, builder.srpm_location)
  File "/usr/lib/python3.4/site-packages/tito/release/copr.py", line 73, in _submit_build
    print(run_command(cmd_submit))
  File "/usr/lib/python3.4/site-packages/tito/common.py", line 398, in run_command
    raise RunCommandException(command, status, output)
tito.exception.RunCommandException: Error running command: /usr/bin/copr-cli build paper-icon-theme paper-icon-theme-1.0-1.src.rpm
```

`srpm_location` is probably not being passed properly to the Copr command line tool.
When I run `copr-cli build /tmp/titp/paper-icon-theme paper-icon-theme-1.0-1.src.rpm` everything works fine.

**Comment by dgoodwin** [comment] 2015-12-01 12:21
Could you provide output from a run with --debug and ideally a link to the source repo where I could try dry-run builds. (if not the spec file would suffice)

**Comment by user501254** [comment] 2015-12-01 22:25
Tito debug log: [tito-debug.txt](https://github.com/dgoodwin/tito/files/49132/tito-debug.txt)
Source: [paper-icon-theme/testing](https://github.com/user501254/paper-icon-theme/tree/testing)

I also tried installing tito from the git repo using the instructions provide in the README.md file but failed to run it so I am using the package available in the fedora repos.
Error log:

    [ashesh@MISTRI tito-master] $ tito --help
    Traceback (most recent call last):
      File "/usr/bin/tito", line 4, in <module>
        __import__('pkg_resources').run_script('tito==0.6.2', 'tito')
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 735, in run_script
        self.require(requires)[0].run_script(script_name, ns)
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1659, in run_script
        exec(script_code, namespace, namespace)
      File "/usr/lib/python2.7/site-packages/tito-0.6.2-py2.7.egg/EGG-INFO/scripts/tito", line 19, in <module>
        
      File "build/bdist.linux-x86_64/egg/tito/cli.py", line 22, in <module>
      File "build/bdist.linux-x86_64/egg/tito/common.py", line 31, in <module>
    ImportError: No module named blessings

**Comment by xsuchy** [comment] 2016-09-13 06:58
It seems you do not have installed python-blessings. Tito.spec have it correctly in requires so there when user use package, there should be no problem.

**Comment by FrostyX** [comment] 2020-04-18 15:50
Hello @user501254,
thank you for the report. I was not able to reproduce the original issue and we use `CoprReleaser` frequently for years, so I would assume it was fixed in the meantime.

If it still happens to you, feel free to reopen.

**Closed** 2020-04-18 15:50 UTC
Labels: bug, easyfix
