### ISSUE TITLE
tito.builder.Builder using wrong source tar.gz filename

### ISSUE THREAD

**Issue by treydock** [rpm-software-management/tito#301] opened 2017-09-08 17:48 UTC
I setup a releasers.conf like below so that I could build SRPMs without having to run through using MockBuilder and building RPMs.  This was entirely to speed up build processes.  When I switched the releaser section to use Builder instead of MockBuilder, I get errors because the tar.gz in SOURCES is the wrong name.

The source file in spec is websockify-%{version}.tar.gz but the Builder seems to be creating python-websockify-%{version}.tar.gz.

Error:
```
[tdockendorf@test-prov-el7 python-websockify]$ RSYNC_USERNAME=mirror tito release dependencies-el6-develop-source --debug
Will release to the following targets: dependencies-el6-develop-source
Releasing to target: dependencies-el6-develop-source
Importing tito.release.YumRepoReleaser
Using releaser class: <class 'tito.release.main.YumRepoReleaser'>
Parsed custom builder args: {}
Importing tito.builder.Builder
Using builder class: <class 'tito.builder.main.Builder'>
Building in temp dir: /tmp/tito/rpmbuild-python-websockify8jq3wC
Getting latest package info from: /users/sysp/tdockendorf/git/ood-packaging/.tito/packages/python-websockify
Command: awk '{ print $1 ; exit }' /users/sysp/tdockendorf/git/ood-packaging/.tito/packages/python-websockify
Status code: 0
Command output: 0.8.0-1

Command: git ls-remote ./. --tag python-websockify-0.8.0-1 | awk '{ print $1 ; exit }'
Status code: 0
Command output: fe215996859ada15081dace080621e8c6efdad86

Local tag SHA1: fe215996859ada15081dace080621e8c6efdad86
Command: git config remote.origin.url
Status code: 0
Command output: git@github.com:treydock/ood-packaging.git

Command: git config remote.origin.url
Status code: 0
Command output: git@github.com:treydock/ood-packaging.git

Checking for tag [python-websockify-0.8.0-1] in git repo [git@github.com:treydock/ood-packaging.git]
Command: git ls-remote git@github.com:treydock/ood-packaging.git --tag python-websockify-0.8.0-1 | awk '{ print $1 ; exit }'
Status code: 0
Command output: fe215996859ada15081dace080621e8c6efdad86

Remote tag SHA1: fe215996859ada15081dace080621e8c6efdad86
Command: git ls-remote ./. --tag python-websockify-0.8.0-1 | awk '{ print $1 ; exit }'
Status code: 0
Command output: fe215996859ada15081dace080621e8c6efdad86

Command: git rev-list --max-count=1 fe215996859ada15081dace080621e8c6efdad86
Status code: 0
Command output: ad853b8f11a78f6b26eae5bea236b86688270279

Got package metadata: ['0.8.0-1', 'dependencies/python-websockify/']
Working in: /tmp/tito/release-python-websockifyosTPkn
Creating python-websockify-0.8.0.tar.gz from git tag: ad853b8f11a78f6b26eae5bea236b86688270279...
Command: git rev-list --timestamp --max-count=1 ad853b8f11a78f6b26eae5bea236b86688270279 | awk '{print $1}'
Status code: 0
Command output: 1504890284

Command: git archive --format=tar --prefix=python-websockify-0.8.0/ ad853b8f11a78f6b26eae5bea236b86688270279:dependencies/python-websockify/ --output=/tmp/tito/rpmbuild-python-websockify8jq3wC/SOURCES/python-websockify-0.8.0.tar.initial
Status code: 0
Command output: 

git-archive fails if relative dir is not in git tree
Command: git archive --format=tar --prefix=python-websockify-0.8.0/ ad853b8f11a78f6b26eae5bea236b86688270279:dependencies/python-websockify/ --output=/tmp/tito/rpmbuild-python-websockify8jq3wC/SOURCES/python-websockify-0.8.0.tar.initial > /dev/null

Status code: 0

Command output: 

Command: gzip -n -c < /tmp/tito/rpmbuild-python-websockify8jq3wC/SOURCES/python-websockify-0.8.0.tar.tar > /tmp/tito/rpmbuild-python-websockify8jq3wC/SOURCES/python-websockify-0.8.0.tar.gz
Status code: 0
Command output: 

Copying git source to: /tmp/tito/rpmbuild-python-websockify8jq3wC/SOURCES/python-websockify-0.8.0
Command: cd /tmp/tito/rpmbuild-python-websockify8jq3wC/SOURCES/ && tar xzf python-websockify-0.8.0.tar.gz
Status code: 0
Command output: 


Command: ls -lR /tmp/tito/rpmbuild-python-websockify8jq3wC/SOURCES/python-websockify-0.8.0/

Status code: 0

Command output: /tmp/tito/rpmbuild-python-websockify8jq3wC/SOURCES/python-websockify-0.8.0/:
total 8
-rw-r--r-- 1 tdockendorf sysp 2810 Sep  8 13:04 python-websockify.spec
lrwxrwxrwx 1 tdockendorf sysp  208 Sep  8 13:04 websockify-0.8.0.tar.gz -> ../../.git/annex/objects/x3/mf/SHA256E-s288359--f080e40b3f429f39dc557c62c6d715a683100e7c10c557fa376b6dbde23358ce.tar.gz/SHA256E-s288359--f080e40b3f429f39dc557c62c6d715a683100e7c10c557fa376b6dbde23358ce.tar.gz

Looking for .spec in /tmp/tito/rpmbuild-python-websockify8jq3wC/SOURCES/python-websockify-0.8.0
Using file: python-websockify.spec
Command: cp /tmp/tito/rpmbuild-python-websockify8jq3wC/SOURCES/python-websockify-0.8.0.tar.gz /tmp/tito/
Status code: 0
Command output: 

Wrote: /tmp/tito/python-websockify-0.8.0.tar.gz
Creating srpm from spec file: /tmp/tito/rpmbuild-python-websockify8jq3wC/SOURCES/python-websockify-0.8.0/python-websockify.spec
using dist: .el6
Command: rpm --eval '%scl'
Status code: 0
Command output: %scl

error: File /tmp/tito/rpmbuild-python-websockify8jq3wC/SOURCES/websockify-0.8.0.tar.gz: No such file or directory



Traceback (most recent call last):
  File "/usr/bin/tito", line 23, in <module>
    CLI().main(sys.argv[1:])
  File "/usr/lib/python2.7/site-packages/tito/cli.py", line 202, in main
    return module.main(argv)
  File "/usr/lib/python2.7/site-packages/tito/cli.py", line 593, in main
    scratch=self.options.scratch)
  File "/usr/lib/python2.7/site-packages/tito/release/main.py", line 262, in release
    self.builder.srpm(dist=srpm_disttag)
  File "/usr/lib/python2.7/site-packages/tito/builder/main.py", line 228, in srpm
    output = run_command_print(cmd)
  File "/usr/lib/python2.7/site-packages/tito/common.py", line 455, in run_command_print
    raise RunCommandException(command, p.poll(), "\n".join(output))
tito.exception.RunCommandException: Error running command: rpmbuild --define "_source_filedigest_algorithm md5"  --define "_binary_filedigest_algorithm md5"  --eval '%undefine scl' --define "_topdir /tmp/tito/rpmbuild-python-websockify8jq3wC" --define "_sourcedir /tmp/tito/rpmbuild-python-websockify8jq3wC/SOURCES" --define "_builddir /tmp/tito/rpmbuild-python-websockify8jq3wC/BUILD" --define "_srcrpmdir /tmp/tito" --define "_rpmdir /tmp/tito"  --define 'dist .el6' --nodeps -bs /tmp/tito/rpmbuild-python-websockify8jq3wC/SOURCES/python-websockify-0.8.0/python-websockify.spec

[tdockendorf@test-prov-el7 python-websockify]$ ls -la /tmp/tito/rpmbuild-python-websockify8jq3wC/SOURCES
total 28
drwxr-xr-x 3 tdockendorf sysp   153 Sep  8 13:45 .
drwx------ 6 tdockendorf sysp    60 Sep  8 13:45 ..
drwxr-xr-x 2 tdockendorf sysp    65 Sep  8 13:04 python-websockify-0.8.0
-rw-r--r-- 1 tdockendorf sysp  1499 Sep  8 13:45 python-websockify-0.8.0.tar.gz
-rw-r--r-- 1 tdockendorf sysp 10240 Sep  8 13:45 python-websockify-0.8.0.tar.initial
-rw-r--r-- 1 tdockendorf sysp 10240 Sep  8 13:45 python-websockify-0.8.0.tar.tar


```

releasers.conf

```
[dependencies-el6-develop]
releaser = tito.release.YumRepoReleaser
srpm_disttag = .el6
builder = tito.builder.MockBuilder
builder.mock = el6-nonscl
builder.mock_config_dir = mock/
rsync = repo.hpc.osc.edu:/var/www/repos/public/ood/dependencies/develop/el6/x86_64/

[dependencies-el6-develop-source]
releaser = tito.release.YumRepoReleaser
srpm_disttag = .el6
builder = tito.builder.Builder
filetypes = srpm
rsync = repo.hpc.osc.edu:/var/www/repos/public/ood/dependencies/develop/el6/SRPMS/
```

**Comment by FrostyX** [comment] 2024-01-03 15:43
I am sorry there wasn't any progress in years. I am closing this as a duplicate of #398.

**Closed by FrostyX** 2024-01-03 15:43 UTC
Labels: bug
