### ISSUE TITLE
Regression with releases in tags

### ISSUE THREAD

**Issue by ekohl** [rpm-software-management/tito#312] opened 2018-01-02 16:45 UTC
Since 0.6.11 I'm having issues where it creates an incorrect tag. When I tried to tag a package, it created the correct changelog but with an incorrect git tag. https://github.com/theforeman/foreman-packaging/commit/607c00b280cee68f764c8a8055707b8d5928bbee is the commit in question. That created ```rubygem-radcli-1.0.0.fm1_17-1``` but then ```tito release koji-foreman-plugins``` complained it could't find the tag ```rubygem-radcli-1.0.0-1.fm1_17```. Note the release was moved.

A similar regression can be seen with trying to tag https://github.com/theforeman/foreman-packaging/commit/f532f793cb4e385abc040ff428f438aef992d1bf:

```
$ tito tag --keep-version --accept-auto-changelog 
Creating output directory: /tmp/tito
ERROR: Error running command: git log --no-merges --pretty='format:%s (%ae)' --relative nodejs-redux-form-validators-2.1.0.fm1_17-1.fm1_17..HEAD -- .

Status code: 128

Command output: fatal: bad revision 'nodejs-redux-form-validators-2.1.0.fm1_17-1.fm1_17..HEAD'

Traceback (most recent call last):
  File "/usr/bin/tito", line 23, in <module>
    CLI().main(sys.argv[1:])
  File "/usr/lib/python3.6/site-packages/tito/cli.py", line 203, in main
    return module.main(argv)
  File "/usr/lib/python3.6/site-packages/tito/cli.py", line 671, in main
    return tagger.run(self.options)
  File "/usr/lib/python3.6/site-packages/tito/tagger/main.py", line 114, in run
    self._tag_release()
  File "/usr/lib/python3.6/site-packages/tito/tagger/main.py", line 656, in _tag_release
    self._make_changelog()
  File "/usr/lib/python3.6/site-packages/tito/tagger/main.py", line 261, in _make_changelog
    output = self._generate_default_changelog(last_tag)
  File "/usr/lib/python3.6/site-packages/tito/tagger/main.py", line 213, in _generate_default_changelog
    output = run_command(patch_command)
  File "/usr/lib/python3.6/site-packages/tito/common.py", line 426, in run_command
    raise RunCommandException(command, status, output)
tito.exception.RunCommandException: Error running command: git log --no-merges --pretty='format:%s (%ae)' --relative nodejs-redux-form-validators-2.1.0.fm1_17-1.fm1_17..HEAD -- .
```

https://github.com/dgoodwin/tito/commit/3a08af27ceb2e7ab7a5474de9ad6784988a59d56#diff-74b3db0e26955739f2851c5efd932b47 looks like a likely candidate for introducing the regression.

**Comment by dgoodwin** [comment] 2018-01-02 17:35
Hmm, could it have been this somehow? https://github.com/dgoodwin/tito/pull/287/files

**Comment by ekohl** [comment] 2018-01-02 17:37
That's also possible. I'm not familiar with the tito code base or even that well known in the tito workflows. For now I downgraded to the previous version so I could continue working but I'm happy to test changes.

**Comment by dgoodwin** [comment] 2018-01-02 17:37
Or even more likely, https://github.com/dgoodwin/tito/pull/287/files and https://github.com/dgoodwin/tito/pull/278.

**Comment by ekohl** [comment] 2018-01-02 17:47
I'm working in the rpm/develop branch.

**Comment by dgoodwin** [comment] 2018-01-02 17:51
Alright using your second example the tag format still looks to match what it was before, which is good.

```
nodejs-redux-form-validators-2.1.0-1.fm1_17          
nodejs-redux-form-validators-2.1.2-1.fm1_17  
```

So it would appear it's the releaser that is confused.

**Comment by dgoodwin** [comment] 2018-01-02 17:54
Also tito tag --keep-version looks off.

**Comment by dgoodwin** [comment] 2018-01-02 17:57
Steps to reproduce:

  1. git clone git@github.com:theforeman/foreman-packaging.git
  1. git checkout rpm/develop
  1. cd foreman-packaging/nodejs-redux-form-validators
  1. tito tag --keep-version --accept-auto-changelog

I don't immediately know how to reproduce the "release" bug mentioned as it's leading down a git annex rathole.

**Comment by dgoodwin** [comment] 2018-01-02 18:54
@vrutkovs  any chance you have time to look into this? I've been digging this afternoon but it's looking larger than I have time for right now. 

Alternatively we can revert the feature for time being and I'll spin a new release until we can get it sorted out.

So far it looks like the use of a tag_suffix is now broken in that tag now flips to suffix-release, whereas previously it was release-suffix. I think there are a few more issues around writing/reading the previous version info from .tito/packages/packagename, as evidenced in the changelog generation problems mentioned above.  Suffix should be a separate component of the version string you can specify.

Mostly though it's obvious we need a bunch more unit testing over the tag_suffix use case.

**Comment by dgoodwin** [comment] 2018-01-02 19:26
I lied, getting closer to a fix in ^^

**Comment by ekohl** [comment] 2018-01-17 11:36
Anything I can do to help this forward?

**Comment by dgoodwin** [comment] 2018-01-17 12:32
If fixing it is out of the question probably not, I was getting close but I am time strapped and honestly not even a tito user anymore. If anyone has time to help fix please let me know. No more releases until it's fixed at the very least, I hope to find time somewhere for that.

**Comment by ekohl** [comment] 2018-01-17 12:35
I could take a stab at it, but I don't know where your WIP PR left off and what's left to do.

**Comment by dgoodwin** [comment] 2018-01-17 12:42
Looking back, it *might* be fixed in that PR. The parts about cleaning up whether or not configuring package name is supported can be handled as a follow up. I think I stopped in lieu or more manual testing, and more unit tests (if we can come up with any). If you have time to review any code in that PR, try it out, and cite if you can think of any more unit tests and/or add them, maybe we can roll with that today.

**Comment by dgoodwin** [comment] 2018-01-17 12:49
To test code with tito you can checkout the correct git branch and use bin/tito-dev, which should run tito with the code in that branch.

Also you can tito build --rpm --test -i and install tito with tito, provided you don't break something, in which case you just have to re-install tito with dnf.

**Comment by dgoodwin** [comment] 2018-07-24 12:56
All I can do is merge it, build it, and hope for the best, anyone object?

**Comment by markllama** [comment] 2018-07-24 15:57
dgoodwin; giive me a bit more time. Bleh.  I spoke too soon.

**Comment by nqb** [comment] 2018-12-06 13:31
Hello everybody,

I got same issue with `tito` 0.6.11 installed from EPEL with https://gitlab.com/nqb1/hello-doc/.

I installed `tito` from sources and all is working as expected.

**Comment by FrostyX** [comment] 2024-01-03 15:30
> I installed tito from sources and all is working as expected.

This should be fixed now, so I am closing. Feel free to reopen if I understood the discussion incorrectly.

**Closed by FrostyX** 2024-01-03 15:30 UTC
Labels: bug
